### PR TITLE
Add support for displaying flats instead of sharps

### PR DESCRIPTION
**Pull request by jjdelvalle**
I added `line-height` to be `1` because the flat symbol has a longer line height which caused the note containers to be taller than the non-flat ones.

### CODE REVIEW

**Comment by half-adder** [comment]
Nice! I'll be putting this back up online ASAP.

**Comment by half-adder** [comment]
I did some small refactors before merging so I had to make some changes to your stuff but it looks good now!

**Comment by jjdelvalle** [comment]
Hey man, glad it's back online!

Not quite sure why there's `src` and `tmp` now but I'm no webdev

BTW: is this under any license?

**Comment by half-adder** [comment]
Good call I'll add a MIT license.

W.r.t. the `src` and `tmp`. There's a program called gulp which takes the files in src/ and then takes the scss and turns it into css, and also turns javascript es6 (which browsers can't run, but has more modern and convenient features) and compiles it to javascript es2015, which browsers can run.

**Pull request merged**
